workflows:
  maui_android_apk:
    name: MAUI Android APK
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      vars:
        DOTNET_CHANNEL: "8.0"

    scripts:
      - name: Install .NET SDK
        script: |
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          bash dotnet-install.sh --channel $DOTNET_CHANNEL
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --info

      - name: Install MAUI Android workload
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet workload install maui-android

      - name: Restore
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet restore LocationTrackerApp.csproj

      - name: Publish APK
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet publish LocationTrackerApp.csproj -f net8.0-android -c Release -p:AndroidPackageFormats=apk -p:AndroidKeyStore=false

    artifacts:
      - bin/Release/net8.0-android/**/*.apk
